modid = "lapisworks"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{$_project.src}/main/resources",
    { path="{$_project.src}/generated/resources", required=false },
    { modid="hexical" },
    { modid="hierophantics" },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_lapisworks/_export/generated"

[template]
# TODO: change this to point to your actual mod icon
icon = "icon.png"
include = [
    "lapisworks",
    "hexical",
    "hierophantics",
    "hexcasting",
    "hexdoc",
]

[template.extend_render]
"index.css" = "lapisworks:lapisworks.css.jinja"
"index.js" = "lapisworks:lapisworks.js.jinja"

[template.args]
mod_name = "Lapisworks"
author = "Real-Luxof"
show_landing_text = false

[textures.override]
"lapisworks:amel_constructs/diamond_sword" = { texture = "lapisworks:textures/item/amel_dsword_noanim.png" }
"lapisworks:amel_constructs/iron_sword" = { texture = "lapisworks:textures/item/amel_isword_noanim.png" }
"lapisworks:amel_constructs/gold_sword" = { texture = "lapisworks:textures/item/amel_gsword_noanim.png" }
"lapisworks:energy_container" = { texture = "lapisworks:textures/item/energy_container.png" }
"lapisworks:amethyst_stamp" = { texture = "lapisworks:textures/item/amethyst_stamp_3d.png" }
# wtf?? whatever, at least it's never shown in the book.
"lapisworks:amel_constructs/focus_necklace/1_worn" = { texture = "lapisworks:textures/item/focus_necklace_worn.png" }
"lapisworks:amel_constructs/focus_necklace/2_worn" = { texture = "lapisworks:textures/item/focus_necklace2_worn.png" }

[flags]
"lapisworks:no_fulllapixical" = false
"lapisworks:robbie_exalt0" = false
"lapisworks:robbie_exalt1" = false

[extra.hexcasting]
# thank you hierophantics lmao
_pattern_regex = { "!Raw" = '(?P<is_per_world>(registerOnlyForHexdoc|register)|(registerPerWorldOnlyForHexdoc|registerPerWorld))\("(?P<name>[^"]+)"?,\s"(?P<signature>[qweasd]+)",\sHexDir\.(?P<startdir>\w+)' }
_per_world_value = "registerPerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{$_project.src}/main/java/com/luxof/lapisworks/init/Patterns.java"
regex = "{^_pattern_regex}"

# source paths

[_project]
src = "../src"
package = "{src}/main/java/com/luxof/lapisworks"
